#include "SaveGame/TriggerSaveGameDefinition.h"

FTriggerSaveSystemDelegate::FStartToSaveGame		FTriggerSaveSystemDelegate::StartToSaveGame;
FTriggerSaveSystemDelegate::FSaveGameComplete		FTriggerSaveSystemDelegate::SaveGameComplete;
FTriggerSaveSystemDelegate::FStartToLoadGame		FTriggerSaveSystemDelegate::StartToLoadGame;
FTriggerSaveSystemDelegate::FLoadGameComplete		FTriggerSaveSystemDelegate::LoadGameComplete;